### ISSUE TITLE
Prime server bad function call error

### ISSUE THREAD

**Issue by chaitu2chowdary** [kevinkreiser/prime_server#103] opened 2021-04-14 13:50 UTC
2021/04/14 13:10:51.443968 [ERROR] src/prime_server.cpp:455 proxy_t: bad_function_call
1 2021/04/14 13:13:46.470489 POST /route HTTP/1.1

**Comment by kevinkreiser** [comment] 2021-04-14 14:24
please look at existing issues first before reporting a new one. this is a duplicate of #101

**Closed by kevinkreiser** 2021-04-14 14:24 UTC

**Comment by chaitu2chowdary** [comment] 2021-04-14 14:35
Okay. Did not notice it. Thanks and will be waiting for a fix.
