### ISSUE TITLE
Interrupt test failing on Mac OS X Sierra 10.12.6

### ISSUE THREAD

**Issue by tgrushka** [kevinkreiser/prime_server#73] opened 2018-08-14 19:45 UTC
Versions:
commit 9a8ac0e91881317a5f0a50a721e1b78cf87ea8d8 (HEAD -> master, origin/master, origin/HEAD)
Homebrew 1.7.1-242-g0d81ad0
autoconf (GNU Autoconf) 2.69
automake (GNU automake) 1.16.1
glibtool (GNU libtool) 2.4.6

libtool -V:   Apple Inc. version cctools-900
GNU Make 3.81

gcc -v:
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0

make test -j8
  CXX      src/prime_serverd-prime_serverd.o
  CXX      src/libprime_server_la-prime_server.lo
  CXX      src/libprime_server_la-netstring_protocol.lo
  CXX      src/libprime_server_la-zmq_helpers.lo
  CXX      src/libprime_server_la-http_util.lo
  CXX      src/libprime_server_la-http_protocol.lo
  CXX      src/prime_httpd-prime_httpd.o
  CXX      src/prime_proxyd-prime_proxyd.o
  CXX      src/prime_workerd-prime_workerd.o
  CXX      src/prime_echod-prime_echod.o
  CXX      src/prime_filed-prime_filed.o
  CXXLD    libprime_server.la
  CXXLD    prime_serverd
  CXXLD    prime_workerd
  CXXLD    prime_filed
  CXXLD    prime_echod
  CXXLD    prime_proxyd
  CXXLD    prime_httpd
/Applications/Xcode.app/Contents/Developer/usr/bin/make  test/zmq test/netstring test/http test/shaping test/interrupt
  CXX      test/zmq-zmq.o
  CXX      test/netstring-netstring.o
  CXX      test/shaping-shaping.o
  CXX      test/http-http.o
  CXX      test/interrupt-interrupt.o
  CXXLD    test/zmq
  CXXLD    test/shaping
  CXXLD    test/interrupt
  CXXLD    test/netstring
  CXXLD    test/http
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
./test-driver: line 107: 29761 Bus error: 10           "$@" > $log_file 2>&1
FAIL: test/interrupt
PASS: test/zmq
PASS: test/shaping
PASS: test/netstring
PASS: test/http
============================================================================
Testsuite summary for prime_server 0.6.3
============================================================================
# TOTAL: 5
# PASS:  4
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to https://github.com/kevinkreiser/prime_server/issues
============================================================================
make[2]: *** [test-suite.log] Error 1
make[1]: *** [check-TESTS] Error 2
make: *** [check-am] Error 2

Contents of test_suite.log:
==========================================
   prime_server 0.6.3: ./test-suite.log
==========================================

# TOTAL: 5
# PASS:  4
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test/interrupt
====================

=== Testing interrupt ===
                      test_early [PASS]
                       test_loopFAIL test/interrupt (exit status: 138)

**Comment by kevinkreiser** [comment] 2018-08-15 15:49
I'm pretty sure this is a duplicate of #65. Can you confirm whether this is a new unrelated issue or not?

**Comment by MattRiddell** [comment] 2020-01-13 14:31
Change -O2 to -O0 didn't help on my machine

**Comment by MartinCapraro** [comment] 2021-01-26 19:17
@kevinkreiser I am experiencing this on macOS Big Sur 11.1. I tried building the lambda_bug  branch as per @MattRiddell but it doesn't fix the problem.

Homebrew 2.7.5
autoconf (GNU Autoconf) 2.69
automake (GNU automake) 1.16.3
glibtool (GNU libtool) 2.4.6
GNU Make 3.81

libtool -V: Apple Inc. version cctools-973.4

gcc -v:
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin20.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by kevinkreiser** [comment] 2021-01-27 00:54
i need to carve out some time to debug this further sorry for the delays here :frowning_face:

**Comment by MartinCapraro** [comment] 2021-01-27 06:43
@kevinkreiser Hey no problem, thanks for the response :D.

**Comment by kaligrafy** [comment] 2021-02-01 19:26
Same problem here on Catalina
```./test-driver: line 109:  5051 Illegal instruction: 4  "$@" > $log_file 2>&1```

**Closed** 2021-03-19 03:02 UTC
